### ISSUE TITLE
实习生每日状态提交的文字格式规范和 YAML 格式规范

### ISSUE THREAD

**Issue by pimgeek** [mindpin/briefing#46]
### 实习生每天通过 QQ 发给宋亮的信息格式如下

```
libochao x月y日 的起始状态
  今天的目的
    <在这里描述目的1，例如：实现日历的逻辑>
      <第一步：在这里描述目的1的第一步工作>
      <第二步：在这里描述目的1的第二步工作>
      <第三步：在这里描述目的1的第三步工作>

    <在这里描述目的2，例如：完成 codecademy 中的全部 JS 教程>
      <第一步：在这里描述目的2的第一步工作>
      <第二步：在这里描述目的2的第二步工作>
      <第三步：在这里描述目的2的第三步工作>

    这里可以补充更多目的……

libochao x月y日 的结束状态
  未解决的问题
    未解决的问题1
      <在这里描述问题1的困惑点>
      <在这里给出问题1的截图>
    未解决的问题2
      <在这里描述问题2的困惑点>
      <在这里给出问题2的截图>
    这里可以补充更多未解决的问题……

  已解决的问题
    已解决的问题1
      <在这里描述问题1的解决过程>
    已解决的问题2
      <在这里描述问题2的解决过程>

    这里可以补充更多已解决的问题……

  提交物
    提交物1
      <在这里给出提交物1的描述>
      <在这里给出提交物1的链接>
    提交物2
      <在这里给出提交物2的描述>
      <在这里给出提交物2的链接>

    这里可以补充更多提交物……
```
### 转换为 YAML 的格式如下

``` yaml
- date: 2015.6.1 # 
  members:
    - name: 实习生名字
      begin:
        goals: # ===> 此处是否该写为 数组 形式？我不太确定
          - desc: 目标的描述
            steps: 
              - desc: 计划中操作步骤的描述
                img: 与操作步骤相关的图片
      end:
        unsolved:
          - desc: 未解决问题的描述
            img: 与未解决问题相关的截图
        solved:
          - desc: 已解决问题的描述
            steps: 
              - desc: 某个解决步骤的描述
        submits:
          - desc: 提交物的描述
            link: 提交物的链接
```

实习生每日状态提交规范，详细说明

https://github.com/mindpin/briefing/wiki/%E5%AE%9E%E4%B9%A0%E5%B7%A5%E4%BD%9C%E7%8A%B6%E6%80%81%E8%AE%B0%E5%BD%95%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83-v1
